name: Sync dev -> uat

## Change the branches and on strategies to suit your needs

on:
  push:
    branches:
      - 'dev'
      - 'feature/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'

jobs:
  dev-env-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          # Extract branch name from GITHUB_REF
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = $ENV_NAME"

  dev-to-uat-merge:
    needs: dev-env-print
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@master

      ## Do other actions below before merging
      ## e.g. unit testing, vulnerability scanning etc.
      ## It is here that you may want to do code deployments in dev env after
      ## verifications are done in branches

      - name: Merge dev -> uat
        uses: devmasx/merge-branch@master
        with:
          #type: now
          from_branch: dev
          target_branch: uat
          github_token: ${{ secrets.ZAW_GA_TOKEN }}

      - name: Print success message
        run: echo "Success!!! DEV is now in UAT"

  