name: Verify Prod

## Change the branches and on strategies to suit your needs

on:
  push:
    branches:
      - 'prod'

jobs:
  prod-branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          # Extract branch name from GITHUB_REF
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = $ENV_NAME"

      ## You may do the deployment in Prod here too

      - name: Print success message
        run: echo "Success!!! PROD is good!"