name: Sync uat -> prod

## Change the branches and on strategies to suit your needs

on:
  push:
    branches:
      - 'uat'

jobs:
  uat-to-prod-merge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/uat'
    steps:
      - uses: actions/checkout@master

      - name: Print app name
        run: echo "APP NAME = ${{ vars.APPLICATION_NAME }}"

      - name: Print env name
        run: |
          # Extract branch name from GITHUB_REF
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV NAME = $ENV_NAME"

      ## Do other actions below before merging
      ## e.g. unit testing, vulnerability scanning etc.
      ## Afterwards, you can do deployment in UAT

      - name: Merge uat -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: uat
          target_branch: prod
          github_token: ${{ secrets.ZAW_GA_TOKEN }}

      - name: Print success message
        run: echo "Success!!! UAT is now in PROD"